version: '3.5'
services:
  proxy:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile-nginx
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    networks:
      - proxybackend
  backend:
    depends_on:
        database:
          condition: service_healthy
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - proxybackend
      - backenddb
  database:
    image: mysql
    restart: always
    healthcheck:
      test: "/usr/bin/mysql -u root -ppassword --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 10
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backenddb

networks:
  proxybackend:
  backenddb:
