version: '3.5'
services:
  nginx:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxybackend
  backend:
    depends_on:
      - database
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - proxybackend
      - backenddb
  database:
    image: mysql

    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backenddb

networks:
  proxybackend:
  backenddb:
